In [ ]:
# pandas, numpy, seaborn, matplotlib, scikit-learn
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# sklearn preprocessing tools: StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
#  sklearn imputer: SimpleImputer
from sklearn.impute import SimpleImputer

# Display settings
plt.style.use('seaborn-v0_8-darkgrid')
%matplotlib inline
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 100)

In [6]:
import seaborn as sns
# === LOAD THE DATA ===
# Load Titanic dataset from seaborn
# Save as titanic_raw - this is our Original backup copy of the data
titanic_raw = sns.load_dataset('titanic')

In [7]:
# === FIRST LOOK AT THE DATA ===
# Display the first 10 rows of the dataset
titanic_raw.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [8]:
# === ESSENTIAL WORKFLOW ===
#  shape - how big is the data?
print("Shape of the dataset:", titanic_raw.shape)

Shape of the dataset: (891, 15)

In [9]:
# info() - what are the data types and non-null counts (what's missing?)
print(titanic_raw.info())

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB
None

In [10]:
# describe - what are the summary statistics for numeric columns?
print(titanic_raw.describe())

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [26]:
# === STEP 1: CHECK FOR DUPLICATES ===
#  create working copy: df = titanic_raw.copy()
# count duplicates : df.duplicated().sum()
df = titanic_raw.copy()
df.drop_duplicates()
# print(f"Duplicate rows: {df.duplicated().sum()}")
print(f"Rows after removing duplicates: {df.shape}")

Rows after removing duplicates: (891, 15)

In [12]:
# EXAMPLE : what duplicates look like
duplicates_df = df[df.duplicated(keep=False)]
duplicates_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
29,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
32,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True

In [15]:
duplicates_df.sort_values(['pclass','who']).head(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
485,0,3,female,NaN,3,1,25.4667,S,Third,woman,False,NaN,Southampton,no,False
133,1,2,female,29.00,1,0,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
300,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
409,0,3,female,NaN,3,1,25.4667,S,Third,woman,False,NaN,Southampton,no,False
573,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
369,1,1,female,24.00,0,0,69.3000,C,First,woman,False,B,Cherbourg,yes,True
368,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
180,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
186,1,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,yes,False
415,0,3,female,NaN,0,0,8.0500,S,Third,woman,False,NaN,Southampton,no,True
198,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
358,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
347,1,3,female,NaN,1,0,16.1000,S,Third,woman,False,NaN,Southampton,yes,False
612,1,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,yes,False
229,0,3,female,NaN,3,1,25.4667,S,Third,woman,False,NaN,Southampton,no,False
241,1,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
274,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
641,1,1,female,24.00,0,0,69.3000,C,First,woman,False,B,Cherbourg,yes,True
359,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True

In [29]:
# === REMOVE DUPLICATES ===
#  Use drop_duplicates() to remove duplicates
# Show before/after row counts
print(f"Rows before removing duplicates: {df.shape}")
clean_data = df.drop_duplicates()
print(f"Rows after removing duplicates: {clean_data.shape}")

Rows before removing duplicates: (891, 15)
Rows after removing duplicates: (784, 15)

In [25]:
print(f"Rows after removing duplicates: {df.shape}")

Rows after removing duplicates: (891, 15)

In [ ]:
# === DUPLICATES ON SPECIFIC COLUMNS ===
# Check for duplicates based on 'pclass' and 'who'
duplicate_subset = df.duplicated(subset=['pclass', 'who'])
# Keep first or last occurrence
print(f"Duplicate rows based on 'pclass' and 'who': {duplicate_subset.sum()}")

In [31]:
print(clean_data.info())

<class 'pandas.DataFrame'>
Index: 784 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     784 non-null    int64
 1   pclass       784 non-null    int64
 2   sex          784 non-null    str
 3   age          678 non-null    float64
 4   sibsp        784 non-null    int64
 5   parch        784 non-null    int64
 6   fare         784 non-null    float64
 7   embarked     782 non-null    str
 8   class        784 non-null    category
 9   who          784 non-null    str
 10  adult_male   784 non-null    bool
 11  deck         202 non-null    category
 12  embark_town  782 non-null    str
 13  alive        784 non-null    str
 14  alone        784 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 77.0 KB
None

In [35]:
# === STEP 2: MISSING VALUES ANALYSIS ===
# Count missing values: df.isnull().sum()
# Calculate missing percentage: (df.isnull().sum() / len(df)) * 100
import pandas as pd

missing_counts = clean_data.isnull().sum()
missing_pct = (missing_counts / len(clean_data)) * 100
missing_df = pd.DataFrame(
    {
        'Missing Count': missing_counts,
        'Missing Percentage': missing_pct
    }
)
# print(missing_df)

missing_df[missing_df['Missing Count'] > 0]

             Missing Count  Missing Percentage
age                    106           13.520408
embarked                 2            0.255102
deck                   582           74.234694
embark_town              2            0.255102

In [37]:
# === STEP 2a: DROP SPARSE COLUMNS ===
# Drop columns with more than 50% missing values
# Drop 'deck' column (77% missing)
print(f"Number of columns before dropping sparse columns: {len(clean_data.columns)}")
clean_data_with_column_removed = clean_data.drop(columns=['deck'])
print(f"Number of columns after dropping sparse columns: {len(clean_data_with_column_removed.columns)}")

Number of columns before dropping sparse columns: 15
Number of columns after dropping sparse columns: 14

In [38]:
clean_data_with_column_removed.info()

<class 'pandas.DataFrame'>
Index: 784 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     784 non-null    int64
 1   pclass       784 non-null    int64
 2   sex          784 non-null    str
 3   age          678 non-null    float64
 4   sibsp        784 non-null    int64
 5   parch        784 non-null    int64
 6   fare         784 non-null    float64
 7   embarked     782 non-null    str
 8   class        784 non-null    category
 9   who          784 non-null    str
 10  adult_male   784 non-null    bool
 11  embark_town  782 non-null    str
 12  alive        784 non-null    str
 13  alone        784 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 75.9 KB

# SimpleImputer: The Professional Approach to Handling Missing Data
WHY USE SimpleImputer INSTEAD OF fillna()?

fillna() is great for quick exploratory work.
SimpleImputer is designed for production-ready data preprocessing because :

1. CONSISTENCY: SimpleImputer ensures the same imputation strategy is applied across all datasets (train, test, new data) by fitting on the training data and transforming consistently. It remembers the imputation values, preventing data leakage and ensuring reproducibility.

2. PIPELINE INTEGRATION: SimpleImputer can be seamlessly integrated into scikit-learn pipelines, allowing for streamlined preprocessing and model training in a single workflow.

3. options: SimpleImputer offers various imputation strategies (mean, median, most_frequent, constant) and can handle both numerical and categorical data effectively.

In [41]:
# pandas, numpy, seaborn, matplotlib, scikit-learn
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# sklearn preprocessing tools: StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
#  sklearn imputer: SimpleImputer pip install scikit-learn
from sklearn.impute import SimpleImputer
# === STEP 2b: FILL AGE WITH SIMPLEIMPUTER ===
# Create SimpleImputer with strategy='median' for 'age' column
age_imputer = SimpleImputer(strategy='median')
# Fit and transform the 'age' column
clean_data_with_column_removed['age'] = age_imputer.fit_transform(clean_data_with_column_removed[['age']])
# CHECK IMPUTER.STATISTICS_ - this shows the median value used for imputation
print(f"Median age used for imputation: {age_imputer.statistics_[0]}")
# Verify that there are no more missing values in 'age'.
print(f"Missing values in 'age' after imputation: {clean_data_with_column_removed['age'].isnull().sum()}")

Median age used for imputation: 28.25
Missing values in 'age' after imputation: 0

# Advanced: Group-Specific Imputation with SimpleImputer
Sometimes the overall median isn't the best choice for imputation, especially when different groups in the data have distinct distributions. In such cases, you can perform group-specific imputation using SimpleImputer.